### ISSUE TITLE
Feature request: Option to change the contact details per property

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#10]
Sometimes a property is sold by different agents. It would be nice if you could select the agent on a per property basis. 

Now it works like the one who creates the porperty is in fact the onwer. But I think it would be better if that is selectable.

**Comment by Coderberg** [comment]
I'll think about it

**Comment by Coderberg** [comment]
Feature Released https://github.com/Coderberg/ResidenceCMS/releases/tag/v1.5.0
