### ISSUE TITLE
Feature request: Ability to select the currency of the price

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#11]
It would be nice if the currency of a property is selectable, or if you can change the default currency system wide. Now it shows a dollar sign.

**Comment by Coderberg** [comment]
you're right

**Comment by Coderberg** [comment]
Done https://github.com/Coderberg/ResidenceCMS/releases/tag/v1.4.2

**Comment by parijke** [comment]
Great, it works!
