### ISSUE TITLE
Не пускает в админку

### ISSUE THREAD

**Issue by yuri25** [Coderberg/ResidenceCMS#12]
Ничего не делал - почему то нет доступа в админ панель:(

![image](https://user-images.githubusercontent.com/253228/66223613-90520a00-e6dc-11e9-97cf-36c5ce3d495d.png)

В чем может быть проблема?

**Comment by yuri25** [comment]
В базе данных в таблице user такие данные:
id  int(11)                                    1
full_name  varchar(255)             John Smith
username  varchar(255)             admin
phone  varchar(255)                   0(0)99766899
email  varchar(255)                     admin@admin
password  varchar(255)               $argon2id$v=19$m=65536,t=4,p=1$tAUiy/hmpKy8QzOwFXJw/A$2aDUW4/bdAcRZRtcdc5hq6HKmIBTfAfg4/wWm3eoMpE
roles  json                                    ["ROLE_ADMIN"]

Вот в поле password так и должно быть? Мне кажется что там не только пароль а до пароля еще какие то данные....

**Comment by Coderberg** [comment]
Попробуйте очистить Cookie в браузере

P.S. У меня в базе вот такой хэш пароля admin: $argon2id$v=19$m=65536,t=4,p=1$VE42SlpualZWUHhYeWMxSA$YiB2lbzspBREzeck9VPCKR3wiT5bXCoh/WCVjMSwsqQ

**Comment by parijke** [comment]
Can we please do this in English as most devs speak English

**Comment by Coderberg** [comment]
To solve the problem with authorization, try to remove  'var' folder and clear cookies from your browser.

**Comment by yuri25** [comment]
Reinstalled the system completely, now in my password field such a hash:
$2y$13$kD2aH1QEmPpaishhHkytheA4Cc8iSW2M2fou1jWkG7x36F2C3L/u6

This data is now missing in the password field, but everything works correctly.
$argon2id$v=19$m=65536,t=4,p=

**Comment by parijke** [comment]
Try 
bin/console doctrine:query:sql "UPDATE user SET password = 'the password in hash' WHERE username = 'admin';"

**Comment by parijke** [comment]
And if algorithm: auto it is posible your system does not work with argon2. SQL another user you know the password of and change the hashed password to the password you know in the database

**Comment by yuri25** [comment]
I can’t understand why now, after reinstalling the system, I do not have this data in the password field
$ argon2id $ v = 19 $ m = 65536, t = 4, p =
But the password hash itself is present and everything works fine. Is this so provided when installing the system or what?
