### ISSUE TITLE
Make error red

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#14]
Suggestion to make errors red to make them more obvious

![image](https://user-images.githubusercontent.com/7671998/70050161-a130d600-15ce-11ea-9bee-c35930500183.png)

**Comment by Coderberg** [comment]
Done https://github.com/Coderberg/ResidenceCMS/commit/0bc4f3b5044af1df3a1bfc31cab4cd813628bf38#diff-783428f1e033e1832564ff345d2f32e3
