### ISSUE TITLE
Feature request: expand search form with features

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#15]
Expand the search form with an extra field / fields to select features. For example:
I want to search all properties with Air Conditioning AND Balcony

![image](https://user-images.githubusercontent.com/7671998/70051335-1e5d4a80-15d1-11ea-8b13-17f3cf888166.png)

**Comment by djpatzo** [comment]
Hi, @parijke 
There is a pull request opened for your issue - https://github.com/Coderberg/ResidenceCMS/pull/31

**Comment by djpatzo** [comment]
The feature for filter is created and merged into master
