### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yuri25** [Coderberg/ResidenceCMS#17]
At the end of the migration, such errors were issued:
php bin/console doctrine:migrations:migrate
```
Migration 20191107180849 failed during Execution. Error An exception occurred wh           ile executing 'ALTER TABLE area CHANGE city_id city_id INT NOT NULL':

SQLSTATE[HY000]: General error: 1832 Cannot change column 'city_id': used in a f           oreign key constraint 'FK_D7943D6888823A92'

In AbstractMySQLDriver.php line 106:

  An exception occurred while executing 'ALTER TABLE area CHANGE city_id city
  _id INT NOT NULL':

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'city_id': used i
  n a foreign key constraint 'FK_D7943D6888823A92'


In PDOConnection.php line 80:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'city_id': used i
  n a foreign key constraint 'FK_D7943D6888823A92'


In PDOConnection.php line 75:

  SQLSTATE[HY000]: General error: 1832 Cannot change column 'city_id': used i
  n a foreign key constraint 'FK_D7943D6888823A92'
```

php bin/console doctrine:fixtures:load

```
 Careful, database "nptz" will be purged. Do you want to continue? (yes/no) [no]:
 > yes

   > purging database

In AbstractMySQLDriver.php line 42:

  An exception occurred while executing 'DELETE FROM metro':

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nptz.metro' doesn't exist


In PDOConnection.php line 43:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nptz.metro' doesn't exist


In PDOConnection.php line 41:

  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nptz.metro' doesn't exist

```

**Comment by Coderberg** [comment]
Is it clean installation or update?

**Comment by parijke** [comment]
Had the same (update). I did a schema update which fixed it but the
migration is not correct.

Op vr 6 dec. 2019 20:22 schreef Valery Maslov <notifications@github.com>:

**Comment by Coderberg** [comment]
Unfortunately I have been unable to reproduce this bug.

### Possible solution: ###
Before you run migration command , go to the ```src/Migrations/Version20191107180849.php``` and remove two line of code
```
$this->addSql('ALTER TABLE area CHANGE city_id city_id INT NOT NULL');
$this->addSql('ALTER TABLE property CHANGE deal_type_id deal_type_id INT NOT NULL, CHANGE city_id city_id INT NOT NULL');
```

**Comment by yuri25** [comment]
I have a clean install...

**Comment by yuri25** [comment]
I commented out these two lines and the installation was successful. But after all, those two drains were needed ... You need to think about what is wrong with them ...

**Comment by Coderberg** [comment]
I've made some changes https://github.com/Coderberg/ResidenceCMS/commit/c7ae7cdc9ee834b6c751db7d7b66ef981dd342c2

**Comment by Coderberg** [comment]
Can someone please try to reproduce this bug?

**Comment by yuri25** [comment]
I tried again, deleted everything, a clean installation 
![image](https://user-images.githubusercontent.com/253228/70378681-5ac3da00-1934-11ea-9035-e9f8304950ab.png)

**Comment by yuri25** [comment]
mysql --version
mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper

**Comment by Coderberg** [comment]
On your screenshot I see not the latest version of Version20191107180849.php

Update to the Latest Version using `git pull`

Or install app using
```
git clone https://github.com/Coderberg/ResidenceCMS.git your_website_directory
cd your_website_directory
composer install
php bin/console doctrine:database:create --no-interaction
php bin/console doctrine:migrations:migrate --no-interaction
php bin/console doctrine:fixtures:load --no-interaction
```

**Comment by yuri25** [comment]
Yes, everything worked correctly without errors. Thank you very much!
