### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#20]
Hi Coderberg, in the code I can see you have anticipated on translations. If you like, I can take care of the dutch translation

**Comment by Coderberg** [comment]
Hi! You can contribute to /translations/messages.nl.xlf

**Comment by parijke** [comment]
I will, do you know a program or online tool to edit xliff files?

**Comment by Coderberg** [comment]
Any code editor (e.g. Visual Studio Code https://code.visualstudio.com/)
