### ISSUE TITLE
Styling not loading

### ISSUE THREAD

**Issue by alex-muchiri** [Coderberg/ResidenceCMS#25]
Please assist on the issue of styling not loading correctly after installation.
![image](https://user-images.githubusercontent.com/13346171/87589417-dfa67b80-c6ed-11ea-95b5-ba809c0a23ec.png)

**Comment by parijke** [comment]
Think you habe to run npm install

**Comment by alex-muchiri** [comment]
I have installed npm and also did npm run dev but still styling ain't loading.

**Comment by parijke** [comment]
try bin/console cache:clear. If that not helps try bin/console assets:install public --symlink

**Comment by alex-muchiri** [comment]
I've installed npm, tried also with yarn. I've also tried to clear my cache and installing public symlink but still the styles are not loading.

**Comment by Coderberg** [comment]
Hi, use please `yarn encore production`

**Comment by alex-muchiri** [comment]
![image](https://user-images.githubusercontent.com/13346171/88089574-e8d39480-cb94-11ea-8703-9cf08628de36.png)

I have tried _'yarn encore production'_ but still not working. What might be the issue?

**Comment by Coderberg** [comment]
Check your web server settings

**Comment by alex-muchiri** [comment]
How should my web server settings look like?

**Comment by Coderberg** [comment]
To run the application locally, use the [local web server](https://symfony.com/doc/current/setup/symfony_server.html) provided by the symfony binary.


1. Install Symfony CLI https://symfony.com/download

2. Run built in web server
```
cd my-project/
symfony server:start
```

**Comment by alex-muchiri** [comment]
> To run the application locally, use the [local web server](https://symfony.com/doc/current/setup/symfony_server.html) provided by the symfony binary.
> 
> 1. Install Symfony CLI https://symfony.com/download
> 2. Run built in web server
> 
> ```
> cd my-project/
> symfony server:start
> ```

This worked, thank you.
