### ISSUE TITLE
Cyrillic slug and paths, do not work

### ISSUE THREAD

**Issue by djpatzo** [Coderberg/ResidenceCMS#28]
I found problem, with cyrillic routes, eg. path/slug.

I will try to fix this and will make pull request.

Also, I will translate ResidenceCMS to Bulgarian and will make additional pull request for this.

**Comment by Coderberg** [comment]
These 2 commits were supposed to completely resolve all the issues with Slugger:

https://github.com/Coderberg/ResidenceCMS/commit/679ca48c2bd53b466bfba73ec3a1874aca0d461a
https://github.com/Coderberg/ResidenceCMS/commit/c49a2f20a4946ee4dd69127bf0f7d0b8611874a9

Please reopen the issue if not all problems have been resolved
