### ISSUE TITLE
Question: what is the roadmap for this?

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#3]
Hi Coderberg,

Really love this install. It has almost everything I need. Just curious what the plans are for the future?

Thanks for sharing this nice peace of work!

**Comment by Coderberg** [comment]
Thank you Paul.
I have no specific roadmap, but I'm planning seriously about it now...

**Comment by parijke** [comment]
That is fantastic. If need any help I am willing to
