### ISSUE TITLE
Feature: multiple file upload

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#4]
Hi Coderberg,

It would be very nice if it was possible to upload more images at the same time. Really a time saver.

**Comment by Coderberg** [comment]
Hi Paul, 
This is planned for the future.

**Comment by parijke** [comment]
That is great!

**Comment by Coderberg** [comment]
This functionality is implemented in version 1.4.0

**Comment by parijke** [comment]
Great, Dropzone works as a charm
