### ISSUE TITLE
Documentation: How to upgrade

### ISSUE THREAD

**Issue by parijke** [Coderberg/ResidenceCMS#5]
Hi Coderberg,

It would be nice to explain in the readme how to upgrade from 1.3.2 to 1.3.3. I had to do a complete new install cause I did not know how.

**Comment by Coderberg** [comment]
Hi.
You can clone this repository
```
git clone https://github.com/Coderberg/ResidenceCMS.git
```
 And for updating use git pull
```
git pull
```
