### ISSUE TITLE
Ошибка версии MariaDB при установке

### ISSUE THREAD

**Issue by aklimov111** [Coderberg/ResidenceCMS#53]
Здравствуйте! MariaDB 10.3.29, но при установке выдает ошибку:

In AbstractMySQLDriver.php line 98:

  An exception occurred while executing 'ALTER TABLE users RENAME INDEX uniq_8d93d649f85e0677 TO
  UNIQ_1483A5E9F85E0677':

  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; c
  heck the manual that corresponds to your MariaDB server version for the right syntax to use nea
  r 'INDEX uniq_8d93d649f85e0677 TO UNIQ_1483A5E9F85E0677' at line 1

https://snipboard.io/JRTjOG.jpg

Какую версию необходимо использовать?

**Comment by Coderberg** [comment]
Здравствуйте @aklimov111 . Проблема исправлена в ветке **[develop](https://github.com/Coderberg/ResidenceCMS/tree/develop)**.

Переключитесь на ветку develop и выполните:

```
composer install
php bin/console app:install
```

P.S. И не забудьте указать свою версию MariaDB в переменной DATABASE_URL

```
DATABASE_URL=mysql://db_user:db_password@127.0.0.1:3306/db_name?serverVersion=mariadb-10.3.29
```

**Comment by aklimov111** [comment]
Спасибо за помощь
