### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by g12345v** [Coderberg/ResidenceCMS#87]
Hello  I have problem in step 2  

  Could not find package coderberg/residence-cms with stability stable in a v
  ersion installable using your PHP version, PHP extensions and Composer vers
  ion.
![123](https://user-images.githubusercontent.com/111237244/184543311-c34c3177-b857-427b-b0a3-0ec383ba572b.JPG)

Does anyone has solution for this?

**Comment by Coderberg** [comment]
Hello @g12345v 
What Version of PHP/Composer are you using on your server?
```shell
php -v
composer -V
```

**Comment by g12345v** [comment]
my php ver 8.1.6   
Composer Ver 2.3.10 
I use xampp v3.3.0

I've already finished  step 2

now I'm in step 3

I'm the beginner , don't know or understand
- (step 4)how to configure web server's document / web root to be the public directory. 
- (step 5) Create .env.local from .env file and fill in your database credentials 
- (step 6)Run  $ php bin/console app:install
-(step 8) To use feedback forms, configure MAILER_DSN in .env.local

Tests
-Modify your DATABASE_URL config in .env.test.local

-Execute this command to run tests:

php bin/php unit

Could you please explain [how to] and [which file / folder] I need to  configure , run code etc?

Thank you.

**Comment by Coderberg** [comment]
@g12345v What operating system are you running XAMPP on?

**Comment by g12345v** [comment]
Microsoft Windows 10

**Comment by Coderberg** [comment]
@g12345v Sorry for the long wait.

The sequence of actions should be something like this:

1. Enable the GD extension by uncommenting the following line in the xampp/php/php.ini:
```ini
extension=gd
```

2. Click the "Shell" button in the XAMPP control panel

3. In the terminal that opens, enter these commands:
```shell
cd htdocs
composer create-project coderberg/residence-cms mywebsite.loc
cd mywebsite.loc
```

4. In the `C:\xampp\htdocs\mywebsite.loc` folder, create a file named `.env.local` with the following content:
```dotenv
APP_ENV=dev
APP_SECRET=6feff92fb5278f215ddca9545d19fcd3
DATABASE_URL="mysql://root:@127.0.0.1:3306/residence"
MAILER_DSN=null://localhost
LANGUAGE_CODE=en
LOCK_DSN=flock
```

5. In the open terminal, run the command:
```shell
php bin/console app:install
```

6. Open the file C:\xampp\apache\conf\extra\httpd-vhosts.conf and add the following lines to the end:

```
<VirtualHost *:80>
    DocumentRoot "C:/xampp/htdocs/mywebsite.loc/public"
    ServerName mywebsite.localhost
    ServerAlias mywebsite.localhost
 
    ErrorLog "logs/mywebsite.log"
    CustomLog "logs/mywebsite.log" common
</VirtualHost>
```

7. Restart the Apache module (Stop/Start button).

8. Go to http://mywebsite.localhost/

**Comment by g12345v** [comment]
it worked ,Thank you so much!!! @Coderberg
