### ISSUE TITLE
Как загрузить изображения в слайдер?

### ISSUE THREAD

**Issue by yuri25** [Coderberg/ResidenceCMS#9]
Валерий здравствуйте. Прекрасная работа! Подскажи пожалуйста что нужно сделать, чтобы изображения, которые я загрузил к объекту недвижимости появились в слайдере к объявлению. Я загрузил несколько фото к объявлению, но они не показываются в слайдере и их нет при редактировании фото объявления. В тех объявлениях, что идут с установкой системы изображения присутствуют, но после добавления новых фото то их потом тоже нет. Или это пока не реализовано? В любом случае спасибо огромное за труды и успехов в проектах. Я первый раз поставил cms на symfony... очень впечатляет.

**Comment by parijke** [comment]
What?

**Comment by Coderberg** [comment]
Здравствуйте, Юрий. 
Все фотографии, добавленные на странице /admin/photo/{id}/edit должны автоматически отображаться в слайдере на странице объекта. 

Возможно у вас какие-то проблемы с загрузкой фотографий. 
Все добавляемые фото должны загружаться в папку /public/uploads/images/full

Проверьте эту папку и соседние папки (large/medium/small). Если ваших фото там нет, значит точно проблема с загрузкой. Она может быть вызвана неправильными настройками в php.ini (может там лимиты какие-то выставлены у вас). Попробуйте увеличить upload_max_filesize, post_max_size, memory_limit).

Я в свою очередь, как будет время, постараюсь сделать вывод ошибок при неудачной загрузке фото.

![GIF](https://user-images.githubusercontent.com/36998159/65952176-26bacd00-e44a-11e9-9853-958c3ab72608.gif)

**Comment by yuri25** [comment]
Спасибо огромное! Мой косяк, в конфигурации домена после перехода с php-fpm на php 7.2 (native) забыл убрать строку `try_files $uri $uri/ /index.php?$args;` в конфиге Nginx.  
Все работает отлично и на php-fpm 7.3.4 и с этой строкой тоже. Чисто моя невнимательность была. Извини пожалуйста если отвлек. Планируете ли расширять функционал? Если не секрет какие планы на проект? С уважением Юрий.

**Comment by Coderberg** [comment]
Планов много, но пока не на всё хватает времени. В будущем, возможно, добавлю в CMS раздел для публикации тематических статей. Ну и мультиязычность хотелось бы запилить в перспективе.

**Comment by parijke** [comment]
If you share the plans, maybe we can work together? Many hands can make work a lot easier

**Comment by Coderberg** [comment]
Yes. This project is open to any pull requests.
